from sqlalchemy import Column, Integer, String, Float, ForeignKey
from .database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    company = Column(String)
    username = Column(String)
    address = Column(String)
    phonenumber = Column(String)
    email = Column(String)
    hashed_password = Column(String)
    industry = Column(String)
    employees = Column(String)

class Answer(Base):
    __tablename__ = "answers"

    id = Column(Integer, primary_key=True, index=True)
    answer_date = Column(String)
    goal = Column(String)
    team_structure = Column(String)
    solo_work = Column(Float)
    remote_work = Column(Float)
    solo_web = Column(Float)
    web_mtg = Column(Float)
    atmosphere = Column(String)
    color = Column(String)
    well_being = Column(String)
    office_capacity = Column(Integer)
    office_size = Column(Integer)
    token = Column(String)  # トークンを格納するフィールドを追加


class Legacy(Base):
    __tablename__ = 'legacy_customers'
    customer_id = Column(Integer, primary_key=True, autoincrement=True)
    category = Column(String)
    image = Column(String)
    color = Column(String)
    solo_work = Column(Integer)
    remote_work = Column(Integer)
    solo_web = Column(Integer)
    web_mtg = Column(Integer)
    well_being_腰痛肩こり対策 = Column(Integer)
    well_being_観葉植物 = Column(Integer)
    well_being_カフェ = Column(Integer)
    well_being_仮眠瞑想 = Column(Integer)
    well_being_アート = Column(Integer)
    well_being_ゲーム = Column(Integer)
    well_being_ライブラリー = Column(Integer)
    well_being_フレックス = Column(Integer)
    goal_成長 = Column(Integer)
    goal_イノベーション = Column(Integer)
    goal_グローバル = Column(Integer)
    goal_リーダーシップ = Column(Integer)
    goal_持続可能性 = Column(Integer)
    goal_地域社会貢献 = Column(Integer)
    goal_多様性 = Column(Integer)
    goal_安心安全 = Column(Integer)
    team_structure_複数の事業を運営する事業別チーム = Column(Integer)
    team_structure_フレキシブルなプロジェクトチーム = Column(Integer)
    team_structure_各分野の専門人材による機能別チーム = Column(Integer)
    team_structure_小規模な一体型チーム = Column(Integer)
    atmosphere_クリエイティブ = Column(Integer)
    atmosphere_スタンダード = Column(Integer)
    atmosphere_フレンドリー = Column(Integer)
    atmosphere_フォーマル = Column(Integer)
    atmosphere_自由 = Column(Integer)
    atmosphere_規律 = Column(Integer)
    atmosphere_オープン = Column(Integer)
    atmosphere_クローズ = Column(Integer)

class Product(Base):
    __tablename__ = 'products'
    product_id = Column(Integer, primary_key=True, index=True)
    category = Column(String)
    image = Column(String)
    color = Column(String)
    product_name = Column(String)
    price = Column(Integer)
    well_being_腰痛肩こり対策 = Column(Integer)
    well_being_観葉植物 = Column(Integer)
    well_being_カフェ = Column(Integer)
    well_being_仮眠瞑想 = Column(Integer)
    well_being_アート = Column(Integer)
    well_being_ゲーム = Column(Integer)
    well_being_ライブラリー = Column(Integer)
    well_being_フレックス = Column(Integer)
    goal_成長 = Column(Integer)
    goal_イノベーション = Column(Integer)
    goal_グローバル = Column(Integer)
    goal_リーダーシップ = Column(Integer)
    goal_持続可能性 = Column(Integer)
    goal_地域社会貢献 = Column(Integer)
    goal_多様性 = Column(Integer)
    goal_安心安全 = Column(Integer)
    team_structure_複数の事業を運営する事業別チーム = Column(Integer)
    team_structure_フレキシブルなプロジェクトチーム = Column(Integer)
    team_structure_各分野の専門人材による機能別チーム = Column(Integer)
    team_structure_小規模な一体型チーム = Column(Integer)
    atmosphere_クリエイティブ = Column(Integer)
    atmosphere_スタンダード = Column(Integer)
    atmosphere_フレンドリー = Column(Integer)
    atmosphere_フォーマル = Column(Integer)
    atmosphere_自由 = Column(Integer)
    atmosphere_規律 = Column(Integer)
    atmosphere_オープン = Column(Integer)
    atmosphere_クローズ = Column(Integer)
    solo_work = Column(Integer)
    remote_work = Column(Integer)
    solo_web = Column(Integer)
    web_mtg = Column(Integer)

class Sale(Base):
    __tablename__ = 'sales'
    id  = Column(Integer, primary_key=True, index=True)
    product_id = Column(Integer, ForeignKey('products.product_id'))
    customer_id = Column(Integer, ForeignKey('users.id'))
    purchase_datetime = Column(String)
    quantity = Column(Integer)